name: Commits Multilinguagem

on:
  schedule:
    - cron: "0 6 * * *"    # Roda Ã s 06:00 UTC (03:00 no Brasil)
    - cron: "0 14 * * *"   # Roda Ã s 14:00 UTC (11:00 no Brasil)
    - cron: "0 22 * * *"   # Roda Ã s 22:00 UTC (19:00 no Brasil)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Atualizar arquivos de vÃ¡rias linguagens
        run: |
          echo "# $(date)" >> ras.py

          git config user.name â€œVictor Pimentaâ€œ
          git config user.email â€œviktorpimenta2705@gmail.comâ€
          git add *
          git commit -m "ğŸ”„ Commit multilinguagem em $(date)"
          git push
